### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by yuyangyg** [meetshah1995/pytorch-semseg#105]
Thanks for your prokect.
I train segnet use NYU2 dadaset  .After several epochs  ,i meet error

Epoch [42/100] Loss: 2.0717
Traceback (most recent call last):
  File "train.py", line 161, in <module>
    train(args)
  File "train.py", line 82, in train
    for i, (images, labels) in enumerate(trainloader):
  File "/home/yuyangyg/anaconda2/envs/pytorch0.3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/home/yuyangyg/anaconda2/envs/pytorch0.3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/home/yuyangyg/anaconda2/envs/pytorch0.3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/yuyangyg/anaconda2/envs/pytorch0.3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/yuyangyg/PycharmProjects/pytorch/pytorch-semseg/ptsemseg/loader/nyuv2_loader.py", line 70, in __getitem__
    img, lbl = self.transform(img, lbl)
  File "/home/yuyangyg/PycharmProjects/pytorch/pytorch-semseg/ptsemseg/loader/nyuv2_loader.py", line 91, in transform
    assert(np.all(classes == np.unique(lbl)))
AssertionError

Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7febafd7aeb8>>
Traceback (most recent call last):
  File "/home/yuyangyg/anaconda2/envs/pytorch0.3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 333, in __del__
    self._shutdown_workers()
  File "/home/yuyangyg/anaconda2/envs/pytorch0.3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 319, in _shutdown_workers
    self.data_queue.get()
  File "/home/yuyangyg/anaconda2/envs/pytorch0.3/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/yuyangyg/anaconda2/envs/pytorch0.3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/home/yuyangyg/anaconda2/envs/pytorch0.3/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/yuyangyg/anaconda2/envs/pytorch0.3/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/yuyangyg/anaconda2/envs/pytorch0.3/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/home/yuyangyg/anaconda2/envs/pytorch0.3/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by meetshah1995** [comment]
`assert(np.all(classes == np.unique(lbl)))` 

This means that that after transformation all classes present in the original target are not present in the transformed target

**Comment by 18022443868** [comment]
> `assert(np.all(classes == np.unique(lbl)))`
> 
> 这意味着在转换后，原始目标中存在的所有类都不在转换后的目标中出现

How to fix category mismatch?
