### ISSUE TITLE
I/O error when training mit_sceneparsing_benchmark.

### ISSUE THREAD

**Issue by IzouGend** [meetshah1995/pytorch-semseg#112]
When I train unet on mit_sceneparsing_benchmark,an io error occured.
OS: ubuntu14.04LTS
Anaconda version:4.2
Python version: 3.5
Platform: pytorch 0.4.0 from source

**Command I used:**
 python train.py \
            --arch unet \
            --dataset mit_sceneparsing_benchmark \
            --img_rows 572 \
            --img_cols 572 \
            --n_epoch 1 \
            --batch_size 1 \
            --no-visdom

**Error Log:** 
4979 iters!
Epoch [1/1] Loss: 1.8828
4999 iters!
Epoch [1/1] Loss: 0.8842
5019 iters!
Epoch [1/1] Loss: 1.7098
5039 iters!
Epoch [1/1] Loss: 1.0830
Traceback (most recent call last):
  File "/home/cuixiongwen/code/pytorch-semseg/train.py", line 164, in <module>
    train(args)
  File "/home/cuixiongwen/code/pytorch-semseg/train.py", line 82, in train
    for i, (images, labels) in enumerate(trainloader):
  File "/home/cuixiongwen/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/cuixiongwen/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/cuixiongwen/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/cuixiongwen/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/cuixiongwen/code/pytorch-semseg/ptsemseg/loader/mit_sceneparsing_benchmark_loader.py", line 73, in __getitem__
    img, lbl = self.augmentations(img, lbl)
  File "/home/cuixiongwen/code/pytorch-semseg/ptsemseg/augmentations.py", line 15, in __call__
    img, mask = Image.fromarray(img, mode='RGB'), Image.fromarray(mask, mode='L')
  File "/home/cuixiongwen/anaconda3/lib/python3.5/site-packages/PIL/Image.py", line 2450, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "/home/cuixiongwen/anaconda3/lib/python3.5/site-packages/PIL/Image.py", line 2403, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
  File "/home/cuixiongwen/anaconda3/lib/python3.5/site-packages/PIL/Image.py", line 2336, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/home/cuixiongwen/anaconda3/lib/python3.5/site-packages/PIL/Image.py", line 788, in frombytes
    raise ValueError("not enough image data")
**ValueError: not enough image data**

**I tried to find the bug,but failed.Could anyone help me? Thank you.**

**Comment by meetshah1995** [comment]
This maybe due to the fact that you're trying to load a black and white image when you're actually expecting 3 channels?

I came across this issue in ADE20k and have added support to catch this behaviour, adding similar type of file handling will prevent this issue.
