### ISSUE TITLE
Error when running ICNet with PascalVOC

### ISSUE THREAD

**Issue by flriancu** [meetshah1995/pytorch-semseg#114]
Hello,

When I run `python train.py --arch icnet --dataset pascal --n_epoch 500`
I get the following output (checked on Windows and Linux, with PyTorch 0.3.1 and 0.4.1)
The dataset is the one [here](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar).

```
Using custom loss
Traceback (most recent call last):
  File "train.py", line 160, in <module>
    train(args)
  File "train.py", line 86, in train
    outputs = model(images)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 68, in forward
    return self.module(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\nn\github\pytorch-semseg\ptsemseg\models\icnet.py", line 120, in forward
    x_sub24, sub4_cls = self.cff_sub24(x_sub4, x_sub2)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\nn\github\pytorch-semseg\ptsemseg\models\utils.py", line 500, in forward
    high_fused_fm = F.relu(low_fm+high_fm, inplace=True)
RuntimeError: The size of tensor a (15) must match the size of tensor b (16) at non-singleton dimension 3
```

Am I doing something wrong? Please let me know if you need more info.

**Comment by adam9500370** [comment]
Due to the interpolation in original Caffe implementation, the input size must be 32*n+1 (n>=1).
Or you can replace the interpolation function (`get_interp_size` in ptsemseg/models/utils.py) with your own implementation.

**Comment by flriancu** [comment]
Thanks, I modified `get_interp_size` to give the proper dimensions (i.e., 16).
Now I have another problem: at the end of the first training epoch, it fails with the following during validation:
```
Traceback (most recent call last):
  File "train.py", line 162, in <module>
    train(args)
  File "train.py", line 110, in train
    outputs = model(images_val)
  File "/home/flr/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/flr/miniconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/flr/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/flr/nn/github/pytorch-semseg/ptsemseg/models/icnet.py", line 113, in forward
    x_sub4 = self.pyramid_pooling(x_sub4)
  File "/home/flr/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/flr/nn/github/pytorch-semseg/ptsemseg/models/utils.py", line 402, in forward
    out = F.avg_pool2d(x, k_sizes[i], stride=strides[i], padding=0)
RuntimeError: Given input size: (1024x8x8). Calculated output size: (1024x1x0). Output size is too small at /pytorch/aten/src/THCUNN/generic/SpatialAveragePooling.cu:63
```

This can be reproduced in standalone code:
```
import torch
import torch.nn.functional as F
from torch.autograd import Variable

x = Variable(torch.zeros([1, 1024, 8, 8]))
out = F.avg_pool2d(x, (8, 15), stride=(5, 10), padding=0)
```

Is this because of the values of `k_sizes` and `strides` in `ptsemseg/utils.py`, or is the input shape incorrect?

**Comment by adam9500370** [comment]
Since the kernel sizes and strides of pyramid pooling in original ICNet implementation are hard-coded,
https://github.com/meetshah1995/pytorch-semseg/blob/dfecf4973c702c9be4b55d5066bd4a79bcb0c1bb/ptsemseg/models/utils.py#L382-L383
you may replace the those lines with the following lines to set `k_sizes` and `strides` appropriately.
https://github.com/meetshah1995/pytorch-semseg/blob/dfecf4973c702c9be4b55d5066bd4a79bcb0c1bb/ptsemseg/models/utils.py#L376-L380

**Comment by flriancu** [comment]
Thanks, solved.

**Comment by yanmu2017** [comment]
@adam9500370 I am facing the same problem now. Do you mind to specify more on how to modify the function `get_interp_size` in ptsemseg/models/utils.py?

**Comment by HareshKarnan** [comment]
still doesnt work for me

**Comment by zhengsz12** [comment]
> @adam9500370 I am facing the same problem now. Do you mind to specify more on how to modify the function `get_interp_size` in ptsemseg/models/utils.py?

Hi，have you solved the problem? I had a same problem.can you help me?

**Comment by zhengsz12** [comment]
> Thanks, solved.

 am facing the similar problem now. Can you tell me how to modify the function get_interp_size in ptsemseg/models/utils.py?Thanks for you help.
