### ISSUE TITLE
Error when running UNet with PascalVOC

### ISSUE THREAD

**Issue by flriancu** [meetshah1995/pytorch-semseg#116]
Hello,

When I run `python train.py --arch unet --dataset pascal --n_epoch 500`
I get the following error
Tested with PyTorch 0.4.1 on Linux.
```
Traceback (most recent call last):
  File "train.py", line 161, in <module>
    train(args)
  File "train.py", line 87, in train
    outputs = model(images)
  File "/home/flr/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/flr/miniconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/flr/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/flr/nn/github/pytorch-semseg/ptsemseg/models/unet.py", line 56, in forward
    up3 = self.up_concat3(conv3, up4)
  File "/home/flr/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/flr/nn/github/pytorch-semseg/ptsemseg/models/utils.py", line 120, in forward
    return self.conv(torch.cat([outputs1, outputs2], 1))
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 24 and 23 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:87
```

Please let me know if you need more info.

**Comment by adam9500370** [comment]
Please check #43.
