### ISSUE TITLE
not enough image data

### ISSUE THREAD

**Issue by 3bobo** [meetshah1995/pytorch-semseg#119]
I run the` fcn8s` model with `ade20k` successfully in the begining, but after 4 hours, it appears an error like this:
```
Traceback (most recent call last):
  File "train.py", line 240, in <module>
    train(args)
  File "train.py", line 110, in train
    for i, (images, labels) in enumerate(trainloader):
  File "/home/neu110/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 322, in __next__
    return self._process_next_batch(batch)
  File "/home/neu110/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/neu110/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/neu110/segmentation/pytorch-semseg/ptsemseg/loader/ade20k_loader.py", line 62, in __getitem__
    img, lbl = self.augmentations(img, lbl)
  File "/home/neu110/segmentation/pytorch-semseg/ptsemseg/augmentations.py", line 16, in __call__
    img, mask = Image.fromarray(img, mode="RGB"), Image.fromarray(mask, mode="L")
  File "/home/neu110/.local/lib/python2.7/site-packages/PIL/Image.py", line 2482, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "/home/neu110/.local/lib/python2.7/site-packages/PIL/Image.py", line 2435, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
  File "/home/neu110/.local/lib/python2.7/site-packages/PIL/Image.py", line 2368, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/home/neu110/.local/lib/python2.7/site-packages/PIL/Image.py", line 799, in frombytes
    raise ValueError("not enough image data")
ValueError: not enough image data
```
the code where the error come from is 
https://github.com/meetshah1995/pytorch-semseg/blob/9a459159f778bdd819955de9650a9edb5fe4ef8b/ptsemseg/loader/ade20k_loader.py#L56
and
https://github.com/meetshah1995/pytorch-semseg/blob/9a459159f778bdd819955de9650a9edb5fe4ef8b/ptsemseg/augmentations.py#L16

and then I tried `mit_sceneparsing_benchmark` datasets,and encountered the same error 
So what the error means? It's because that the augmentations function doesn't work after many epochs ? and how to fix it?

**Comment by 3bobo** [comment]
I replace these code as you said, and  get a good one epoch training process,however, as one epoch training is done, the training data is still nan like this:
```
Epoch [1/100] Loss: 2.1018
Epoch [1/100] Loss: 2.8031
one epoch training done
0it [00:00, ?it/s]
/home/neu110/segmentation/pytorch-semseg/ptsemseg/metrics.py:34: RuntimeWarning: invalid value encountered in double_scalars
  acc = np.diag(hist).sum() / hist.sum()
/home/neu110/segmentation/pytorch-semseg/ptsemseg/metrics.py:35: RuntimeWarning: invalid value encountered in divide
  acc_cls = np.diag(hist) / hist.sum(axis=1)
/home/neu110/segmentation/pytorch-semseg/ptsemseg/metrics.py:36: RuntimeWarning: Mean of empty slice
  acc_cls = np.nanmean(acc_cls)
/home/neu110/segmentation/pytorch-semseg/ptsemseg/metrics.py:37: RuntimeWarning: invalid value encountered in divide
  iu = np.diag(hist) / (hist.sum(axis=1) + hist.sum(axis=0) - np.diag(hist))
/home/neu110/segmentation/pytorch-semseg/ptsemseg/metrics.py:38: RuntimeWarning: Mean of empty slice
  mean_iu = np.nanmean(iu)
/home/neu110/segmentation/pytorch-semseg/ptsemseg/metrics.py:39: RuntimeWarning: invalid value encountered in divide
  freq = hist.sum(axis=1) / hist.sum()
/home/neu110/segmentation/pytorch-semseg/ptsemseg/metrics.py:40: RuntimeWarning: invalid value encountered in greater
  fwavacc = (freq[freq > 0] * iu[freq > 0]).sum()
('FreqW Acc : \t', 0.0)
('Overall Acc: \t', nan)
('Mean Acc : \t', nan)
('Mean IoU : \t', nan)
WARN: resizing labels yielded fewer classes
Epoch [2/100] Loss: 1.0623
Epoch [2/100] Loss: 2.3937
```
By the way, there appears  `WARN: resizing labels yielded fewer classes` durning training process resulting  from this code:
```
if not np.all(classes == np.unique(lbl))
      print("WARN: resizing labels yielded fewer classes")
```
Is that ok for training?

**Comment by adam9500370** [comment]
`0it [00:00, ?it/s]`
You can check whether your validation data path is correct or not. (refer to [this comment](https://github.com/meetshah1995/pytorch-semseg/issues/118#issuecomment-414064160))

`WARN: resizing labels yielded fewer classes`
Since the default input image size is 256x256, lower resolution input may make some small object classes disappear.

**Comment by 3bobo** [comment]
Ok, it works this time.thank you very much!
