### ISSUE TITLE
ICNet error

### ISSUE THREAD

**Issue by david-bernstein** [meetshah1995/pytorch-semseg#146]
Getting an error when trying to train using model icnet, here is the full output:

python train.py --config configs/bdd.yml
RUNDIR: runs/bdd/32825
3500
/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py:482: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if issubdtype(ts, int):
/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py:485: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif issubdtype(type(size), float):
(2, 2)
/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py:1890: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py:1961: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "train.py", line 231, in <module>
    train(cfg, writer, logger)
  File "train.py", line 131, in train
    outputs = model(images)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dave/Desktop/pytorch-semseg-master/ptsemseg/models/icnet.py", line 209, in forward
    x_sub24, sub4_cls = self.cff_sub24(x_sub4, x_sub2)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dave/Desktop/pytorch-semseg-master/ptsemseg/models/utils.py", line 802, in forward
    high_fused_fm = F.relu(low_fm + high_fm, inplace=True)
RuntimeError: The size of tensor a (79) must match the size of tensor b (80) at non-singleton dimension 3

**Comment by adam9500370** [comment]
Hi, @david-bernstein .
You can see #114.
