### ISSUE TITLE
config.yml  for segnet

### ISSUE THREAD

**Issue by yyangmei** [meetshah1995/pytorch-semseg#155]
I want to train segnet, but i don't know how to set the config. Can anyone help me? Thank you so much.
What's more, how should i process the dataset if i use pascal 2012?

**Comment by komms** [comment]
![screenshot from 2018-12-26 16-28-25](https://user-images.githubusercontent.com/35064612/50450388-f4fe5e00-092d-11e9-9c3b-fd0c3b6d56f4.png)

**Comment by amritpaul** [comment]
where is the config.json file? 
Failed to import pydensecrf,           CRF post-processing will not work
Read Input Image from : /semantic_segmentation/cityscapes/leftImg8bit/test/berlin/berlin_000000_000019_leftImg8bit.png
Traceback (most recent call last):
  File "test.py", line 157, in <module>
    test(args)
  File "test.py", line 33, in test
    data_path = get_data_path(args.dataset)
  File "/semantic_segmentation/pytorch-semseg/ptsemseg/loader/__init__.py", line 37, in get_data_path
    data = json.load(open(config_file))
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
