### ISSUE TITLE
Pytorch 0.41 compatible issue

### ISSUE THREAD

**Issue by jinfagang** [meetshah1995/pytorch-semseg#160]
Thanks for the elegant code. I like it, however I got a tensor mistach error:

```
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:2061: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:2133: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "train.py", line 228, in <module>
    train(cfg, writer, logger)
  File "train.py", line 128, in train
    outputs = model(images)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/jintain/sg/ai/career/robot/ctirobot/seg/pytorch-semseg/ptsemseg/models/icnet.py", line 209, in forward
    x_sub24, sub4_cls = self.cff_sub24(x_sub4, x_sub2)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/jintain/sg/ai/career/robot/ctirobot/seg/pytorch-semseg/ptsemseg/models/utils.py", line 802, in forward
    high_fused_fm = F.relu(low_fm + high_fm, inplace=True)
RuntimeError: The size of tensor a (63) must match the size of tensor b (64) at non-singleton dimension 3

```

I am not sure what it happens, but seems it is some default behaviour changes in pytorch lead to this error. Has any one got this?
My enviroment is:

```
➜  pytorch-semseg git:(master) ✗ pip3 list|grep torch
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
torch (0.4.1)
torch-nightly (1.0.0.dev20181106)
torchfcn (1.9.0)
torchfile (0.1.0)
torchvision (0.2.1)

```

**Comment by adam9500370** [comment]
Hi, @jinfagang .
You can see #114 .
