### ISSUE TITLE
icnet training interrupted

### ISSUE THREAD

**Issue by jinfagang** [meetshah1995/pytorch-semseg#162]
Hi, the ICNet training are not really works well, it interrupted with error:

```
Iter [700/300000]  Loss: 567506.8125  Time/Image: 0.0759
Iter [750/300000]  Loss: 284077.2500  Time/Image: 0.0702
Iter [800/300000]  Loss: 821963.0000  Time/Image: 0.0667
Iter [850/300000]  Loss: 348755.8438  Time/Image: 0.0675
Iter [900/300000]  Loss: 695492.8750  Time/Image: 0.0654
Iter [950/300000]  Loss: 458015.0312  Time/Image: 0.0691
Iter [1000/300000]  Loss: 453885.0312  Time/Image: 0.0705
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "train.py", line 230, in <module>
    train(cfg, writer, logger)
  File "train.py", line 159, in train
    outputs = model(images_val)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/jintain/sg/ai/career/robot/ctirobot/seg/pytorch-semseg/ptsemseg/models/icnet.py", line 202, in forward
    x_sub4 = self.pyramid_pooling(x_sub4)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/jintain/sg/ai/career/robot/ctirobot/seg/pytorch-semseg/ptsemseg/models/utils.py", line 585, in forward
    out = F.avg_pool2d(x, k_sizes[i], stride=strides[i], padding=0)
RuntimeError: Given input size: (1024x17x33). Calculated output size: (1024x0x0). Output size is too small at /pytorch/aten/src/THCUNN/generic/SpatialAveragePooling.cu:63

```

**Comment by adam9500370** [comment]
Hi, @jinfagang .
You can see #114 .

**Comment by jinfagang** [comment]
@adam9500370 Hi, thanks for your response, all other problem were all solved except this one.

If you look carefully, this error occurs when evaluation only. I have already set training data target size to 513x1025.

But when evaluation, this error got. Do you have any idea about this? it's something with evaluation data?

**Comment by jinfagang** [comment]
@adam9500370 Hi, seems the stride issue solved, but as you can see, if eval is on, the model returns not a scale list but only one output which not same with train and got this error:


```
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "train.py", line 230, in <module>
    train(cfg, writer, logger)
  File "train.py", line 160, in train
    val_loss = loss_fn(input=outputs, target=labels_val)
  File "/media/jintain/sg/ai/career/robot/ctirobot/seg/pytorch-semseg/ptsemseg/loss/loss.py", line 43, in multi_scale_cross_entropy2d
    size_average=size_average)
  File "/media/jintain/sg/ai/career/robot/ctirobot/seg/pytorch-semseg/ptsemseg/loss/loss.py", line 13, in cross_entropy2d
    n, c, h, w = input.size()
ValueError: not enough values to unpack (expected 4, got 3)

```

But in training code, the loss_fn just same with training when eval. So what's the proper way to change this? Or using 2 different loss_fn depends on what phase is on.

**Comment by adam9500370** [comment]
I think you can add the followings at `multi_scale_cross_entropy2d` function (ptsemseg/loss/loss.py#L31):
```
    if not isinstance(input, tuple):
        return cross_entropy2d(input=input, target=target, weight=weight, size_average=size_average)
```
Calculate cross entropy loss when evaluation only on the output of the highest resolution branch.

**Comment by jinfagang** [comment]
@adam9500370 Thanks, seems this is a proper way to do this.
