### ISSUE TITLE
running the test file

### ISSUE THREAD

**Issue by likui01** [meetshah1995/pytorch-semseg#178]
hi,
i am trying to run the code, and getting the following error, your help is appreciated.   

data = json.load(open(config_file))
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by chris3006** [comment]
After converting to config.json, I go the following error. 

python test.py --model_path runs/Segnet_cityscapes/48080/segnet_cityscapes_best_model.pkl --dataset cityscapes --img_path testin.png --out_path testout.png 

Read Input Image from : testin.png
Traceback (most recent call last):
  File "test.py", line 157, in <module>
    test(args)
  File "test.py", line 33, in test
    data_path = get_data_path(args.dataset)
  File "/scratch-local/cdtemp/christian/pytorch-semseg/ptsemseg/loader/__init__.py", line 37, in get_data_path
    return data[name]["data_path"]
KeyError: 'cityscapes'

Is it legit to use online yaml to json converter ? How to convert to json?
