### ISSUE TITLE
Exception: No files for split=[train_aug] found in /home/lxc/datasets/leftImg8bit/train_aug

### ISSUE THREAD

**Issue by li0128** [meetshah1995/pytorch-semseg#193]

**Comment by li0128** [comment]
Exception: No files for split=[train_aug] found in /home/lxc/datasets/leftImg8bit/train_aug

$ python3 train.py 
RUNDIR: runs/fcn8s_cityscapes/48042
Traceback (most recent call last):
  File "train.py", line 231, in <module>
    train(cfg, writer, logger)
  File "train.py", line 51, in train
    augmentations=data_aug,
  File "/home/lxc/PythonProjects/pytorch-semseg-master/ptsemseg/loader/cityscapes_loader.py", line 136, in __init__
    raise Exception("No files for split=[%s] found in %s" % (split, self.images_base))
Exception: No files for split=[train_aug] found in /home/lxc/datasets/leftImg8bit/train_aug

**Comment by salt0107fish** [comment]
Have you solved your problem? I guess the path for your pictures is wrong.
