### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print' when run train.py

### ISSUE THREAD

**Issue by ysh329** [meetshah1995/pytorch-semseg#24]
After data download and prerequisite installation, I ran commands as below: 
```shell
root@2d5d0934e049:/home/yuanshuai/code/pytorch-semseg# python train.py \                            
> --arch fcn8s \
> --dataset pascal \
> --img_rows 224 \
> --img_cols 224 \
> --n_epoch 1 \
> --batch_size 1 \
> --l_rate 1 \
> --feature_scale 2
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from ptsemseg.loader import get_loader, get_data_path
  File "/home/yuanshuai/code/pytorch-semseg/ptsemseg/loader/__init__.py", line 3, in <module>
    from ptsemseg.loader.pascal_voc_loader import pascalVOCLoader
  File "/home/yuanshuai/code/pytorch-semseg/ptsemseg/loader/pascal_voc_loader.py", line 130
    print "Pre-encoding segmentation masks..."
                                             ^
SyntaxError: Missing parentheses in call to 'print'
```

Any advice or suggestions, thanks in advance!

**Comment by achaiah** [comment]
That's because you're using python 3.x while this project was written in python 2.x

**Comment by ysh329** [comment]
@achaiah Thanks my big brother :rofl:
