### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in __instancecheck__

### ISSUE THREAD

**Issue by wangfusheng-cqu** [meetshah1995/pytorch-semseg#248]
RUNDIR: runs/fcn8s_nyuv2/11739
Traceback (most recent call last):
  File "/home/wangfusheng18/fengeduibifangfa/pytorch-semseg-master/train.py", line 250, in <module>
    train(cfg, writer, logger)
  File "/home/wangfusheng18/fengeduibifangfa/pytorch-semseg-master/train.py", line 118, in train
    for (images, labels) in trainloader:
  File "/home/wangfusheng18/.conda/envs/torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/wangfusheng18/.conda/envs/torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RecursionError: Traceback (most recent call last):
  File "/home/wangfusheng18/.conda/envs/torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wangfusheng18/.conda/envs/torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wangfusheng18/fengeduibifangfa/pytorch-semseg-master/ptsemseg/loader/nyuv2_loader.py", line 83, in __getitem__
    return self.__getitem__(np.random.randint(0, self.__len__()))
  File "/home/wangfusheng18/fengeduibifangfa/pytorch-semseg-master/ptsemseg/loader/nyuv2_loader.py", line 83, in __getitem__
    return self.__getitem__(np.random.randint(0, self.__len__()))
  File "/home/wangfusheng18/fengeduibifangfa/pytorch-semseg-master/ptsemseg/loader/nyuv2_loader.py", line 83, in __getitem__
    return self.__getitem__(np.random.randint(0, self.__len__()))
  [Previous line repeated 959 more times]
  File "/home/wangfusheng18/fengeduibifangfa/pytorch-semseg-master/ptsemseg/loader/nyuv2_loader.py", line 76, in __getitem__
    img = np.load(img_path)
  File "/home/wangfusheng18/.conda/envs/torch0.4.1/lib/python3.6/site-packages/numpy/lib/npyio.py", line 453, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/wangfusheng18/.conda/envs/torch0.4.1/lib/python3.6/site-packages/numpy/lib/format.py", line 712, in read_array
    shape, fortran_order, dtype = _read_array_header(fp, version)
  File "/home/wangfusheng18/.conda/envs/torch0.4.1/lib/python3.6/site-packages/numpy/lib/format.py", line 578, in _read_array_header
    d = safe_eval(header)
  File "/home/wangfusheng18/.conda/envs/torch0.4.1/lib/python3.6/site-packages/numpy/lib/utils.py", line 1139, in safe_eval
    return ast.literal_eval(source)
  File "/home/wangfusheng18/.conda/envs/torch0.4.1/lib/python3.6/ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "/home/wangfusheng18/.conda/envs/torch0.4.1/lib/python3.6/ast.py", line 66, in _convert
    in zip(node.keys, node.values))
  File "/home/wangfusheng18/.conda/envs/torch0.4.1/lib/python3.6/ast.py", line 65, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "/home/wangfusheng18/.conda/envs/torch0.4.1/lib/python3.6/ast.py", line 59, in _convert
    return tuple(map(_convert, node.elts))
  File "/home/wangfusheng18/.conda/envs/torch0.4.1/lib/python3.6/ast.py", line 54, in _convert
    elif isinstance(node, (Str, Bytes)):
RecursionError: maximum recursion depth exceeded in __instancecheck__

**Comment by wangfusheng-cqu** [comment]
Hi, How to deal with it.
