### ISSUE TITLE
KeyError: 'name'

### ISSUE THREAD

**Issue by lewisxiaoxu** [meetshah1995/pytorch-semseg#259]
Traceback (most recent call last):
  File "E:/Semantic Segmentation/pytorch-semseg-master/train.py", line 229, in <module>
    train(cfg, writer, logger)
  File "E:/Semantic Segmentation/pytorch-semseg-master/train.py", line 80, in train
    optimizer_cls = get_optimizer(cfg)
  File "E:\Semantic Segmentation\pytorch-semseg-master\ptsemseg\optimizers\__init__.py", line 24, in get_optimizer
    opt_name = cfg["training"]["optimizer"]["name"]
KeyError: 'name'

**Comment by lewisxiaoxu** [comment]
how to deal with please

**Comment by sudarshan1994** [comment]
Using the below structure in the config file would resolve this
optimizer:

    name:sgd
