### ISSUE TITLE
Error:  assert Y.ndim == 1 or Y.ndim == 2, 'Y should have 1 or 2 dim'

### ISSUE THREAD

**Issue by 4F2E4A2E** [meetshah1995/pytorch-semseg#36]
Hello there!

I am having a huge struggle installing pytorch-semseg. Is it supported on windows x64 ?
I've installed everything on Windows with pytorch for python 3.6 and adapted every print method to python 3 in source code:
```
(pytorch) semseg>pip install -r requirements.txt
Requirement already satisfied: matplotlib==2.0.0 in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: numpy==1.12.1 in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: scipy in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: torchvision==0.1.7 in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: tqdm==4.11.2 in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: visdom==0.1.1 in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: certifi in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from matplotlib==2.0.0->-r requirements.txt (line 1))
Requirement already satisfied: pytz in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from matplotlib==2.0.0->-r requirements.txt (line 1))
Requirement already satisfied: cycler>=0.10 in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from matplotlib==2.0.0->-r requirements.txt (line 1))
Requirement already satisfied: six>=1.10 in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from matplotlib==2.0.0->-r requirements.txt (line 1))
Requirement already satisfied: python-dateutil in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from matplotlib==2.0.0->-r requirements.txt (line 1))
Requirement already satisfied: torch in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from torchvision==0.1.7->-r requirements.txt (line 4))
Requirement already satisfied: pillow in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from torchvision==0.1.7->-r requirements.txt (line 4))
Requirement already satisfied: tornado in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from visdom==0.1.1->-r requirements.txt (line 6))
Requirement already satisfied: requests in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from visdom==0.1.1->-r requirements.txt (line 6))
Requirement already satisfied: pyzmq in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from visdom==0.1.1->-r requirements.txt (line 6))
Requirement already satisfied: pyyaml in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from torch->torchvision==0.1.7->-r requirements.txt (line 4))
Requirement already satisfied: olefile in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from pillow->torchvision==0.1.7->-r requirements.txt (line 4))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from requests->visdom==0.1.1->-r requirements.txt (line 6))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from requests->visdom==0.1.1->-r requirements.txt (line 6))
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\semseg\appdata\local\conda\conda\envs\pytorch\lib\site-packages (from requests->visdom==0.1.1->-r requirements.txt (line 6))
```
Seams good to me.

Started training and got error:
```
(pytorch) semseg>python train.py --arch segnet --dataset pascal --img_rows "512" --img_cols "512"
Traceback (most recent call last):
  File "train.py", line 109, in <module>
    train(args)
  File "train.py", line 36, in train
    legend=['Loss']))
  File "C:\Users\semseg\AppData\Local\conda\conda\envs\pytorch\lib\site-packages\visdom\__init__.py", line 438, in line
    assert Y.ndim == 1 or Y.ndim == 2, 'Y should have 1 or 2 dim'
AttributeError: 'torch.FloatTensor' object has no attribute 'ndim'
```

Can anyone tell me what  i am doing wrong &/ in which constellation (python27 or python36, CUDA 7/8, cuDNN 5/6) i should install pytorch-semseg?

**Comment by 4F2E4A2E** [comment]
Installed cuda 7.5 with cudnn on ubuntu 16.04, it works until #39 now.
Dependencies are installed correctly, CUDA is loading and this error does not show up anymore. Closing issue.
