### ISSUE TITLE
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by <class 'socket.error'>

### ISSUE THREAD

**Issue by xiaofengqing** [meetshah1995/pytorch-semseg#41]
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/visdom/__init__.py", line 262, in _send
    data=json.dumps(msg),
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by <class 'socket.error'>: [Errno 111] Connection refused)

When i try to run train.py，i meet this error，can you give me some suggestion？

**Comment by 4F2E4A2E** [comment]
Did you start the visdom server _before_ starting the training?
```
python -m visdom.server
```

**Comment by xiaofengqing** [comment]
@4F2E4A2E Oh, thank you，the problem was solved.
