### ISSUE TITLE
Module Not Present

### ISSUE THREAD

**Issue by sangeet259** [meetshah1995/pytorch-semseg#47]
running train.py throws the following error
Throwback :

```
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from ptsemseg.models import get_model
  File "/home/du4/14CS30025/sangeet/segmentation/pytorch-semseg/ptsemseg/models/__init__.py", line 8, in <module>
    from ptsemseg.models.frrn import *
ImportError: No module named frrn
```

**Comment by meetshah1995** [comment]
Solved by f793bfb28b0c89245402ed53d35a20c800673721
