### ISSUE TITLE
Dataloader error

### ISSUE THREAD

**Issue by lxtGH** [meetshah1995/pytorch-semseg#75]
Thanks for your code, I was using the cityscape dataloader for training, but I met this error after I train some epoch. Traceback (most recent call last):
  File "train.py", line 165, in <module>
/nas/dataset/cityscape/leftImg8bit/train/dusseldorf/dusseldorf_000197_000019_leftImg8bit.png
    train(args)
  File "train.py", line 77, in train
    for i, batch in enumerate(trainloader):
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/lxt/project/seg-pytorch/dataset/dataloader/cityscapes.py", line 100, in __getitem__
    img = np.array(img, dtype=np.uint8)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'PngImageFile'

Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f7d486d2908>>
Traceback (most recent call last):
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 333, in __del__
    self._shutdown_workers()
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 319, in _shutdown_workers
    self.data_queue.get()
  File "/home/lxt/anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/home/lxt/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/lxt/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/lxt/anaconda3/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/home/lxt/anaconda3/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

I have no idea how to fix it

**Comment by yuyangyg** [comment]
I meet the same problem, can you give me some advice?

**Comment by lxtGH** [comment]
keep the right address of the image list when you load the data
