### ISSUE TITLE
RuntimeError in PyTorch v0.3.0

### ISSUE THREAD

**Issue by sangeet259** [meetshah1995/pytorch-semseg#85]
I have PyTorch version 0.3.0 post4.
Architecture `fcn8s`/`fcn16s`/`fcn32s`
Dataloader : `PasvalVOC`

The code runs fine till `loss = cross_entropy2d(outputs, labels)` in *train.py*. But then it throws a throback in the line `loss.backward()`.

Here is the traceback:
```
$ python3 train.py --arch fcn32s
/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py:1423: UserWarning: nn.functional.upsample_bilinear is deprecated. Use nn.functional.upsample instead.
  warnings.warn("nn.functional.upsample_bilinear is deprecated. Use nn.functional.upsample instead.")
/media/sangeet/Stuff/gitrepo/Machine Learning/pytorch-semseg/ptsemseg/loss.py:9: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  log_p = F.log_softmax(input)
/usr/local/lib/python3.5/dist-packages/torch/autograd/_functions/tensor.py:465: UserWarning: self and mask not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  return tensor.masked_select(mask)
Traceback (most recent call last):
  File "train.py", line 98, in <module>
    train(epochs,args)
  File "train.py", line 68, in train
    loss.backward()
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/function.py", line 91, in apply
    return self._forward_cls.backward(self, *args)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/_functions/tensor.py", line 481, in backward
    grad_tensor = grad_tensor.masked_scatter(mask, grad_output)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/variable.py", line 427, in masked_scatter
    return self.clone().masked_scatter_(mask, variable)
RuntimeError: invalid argument 1: the number of sizes provided must be greater or equal to the number of dimensions in the tensor at /pytorch/torch/lib/TH/generic/THTensor.c:299
```

**Comment by sangeet259** [comment]
The important thing to note is the last line : 
RuntimeError: invalid argument 1: the number of sizes provided must be greater or equal to the number of dimensions in the tensor at /pytorch/torch/lib/TH/generic/THTensor.c:299

**Comment by sangeet259** [comment]
I googled the error, most of them told to install PyTorch from source to avoid this, but that didn't help !
