### ISSUE TITLE
I met a mistake as follows:

### ISSUE THREAD

**Issue by ronyuzhang** [meetshah1995/pytorch-semseg#87]
Traceback (most recent call last):
  File "train.py", line 169, in <module>
    train(args)
  File "train.py", line 92, in train
    outputs = model(images)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 68, in forward
    return self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/zhangyao/jdjr/semantic_segmentation/pytorch-semseg/ptsemseg/models/unet.py", line 56, in forward
    up3 = self.up_concat3(conv3, up4)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/zhangyao/jdjr/semantic_segmentation/pytorch-semseg/ptsemseg/models/utils.py", line 120, in forward
    return self.conv(torch.cat([outputs1, outputs2], 1))
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 23 and 24 in dimension 2 at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/TH/generic/THTensorMath.c:2897

**Comment by L0SG** [comment]
Seems like the size inconsistency issue of U-net (#43). Current implementation of U-net does not support arbitrary image sizes. Could you test with input size 572x572 and output size 388x388?

**Comment by sanshibayuan** [comment]
Just change the size in train_loader to 572x572 and 388x388 for the val_loader
